# Generated by Django 5.2.5 on 2025-10-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата пользователя в Telegram для отправки напоминаний', max_length=64, null=True, verbose_name='Telegram chat ID'),
        ),
    ]
