# Generated by Django 5.2.5 on 2025-10-22 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('time', models.TimeField()),
                ('is_pleasant', models.BooleanField(default=False)),
                ('reward', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('repeat_days', models.PositiveIntegerField(default=1, help_text='Повторность в днях (1..7), по умолчанию ежедневно')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='habits.habit')),
            ],
            options={
                'ordering': ['time', 'id'],
            },
        ),
    ]
