# Generated by Django 5.2.5 on 2025-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
